"""Step 6 - Output: write metrics, validation results and the evidence table."""


def md_table(df):
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for row in df.itertuples(index=False):
        lines.append("| " + " | ".join("" if v is None else str(v) for v in row) + " |")
    return "\n".join(lines)


def pct(x):
    return f"{x:.1%}"


def build_evidence(run_id, metrics, tables, validation, reconciliation):
    m = metrics.set_index("metric_id")
    iv = tables["interventions"]

    headline = metrics[~metrics["metric_id"].str.startswith("M5")].copy()
    headline["value"] = [pct(v) for v in headline["value"]]

    iv_view = iv.assign(late_rate=iv["late_rate"].map(pct),
                        comparable_late_rate=iv["comparable_late_rate"].map(pct),
                        naive_baseline=iv["naive_baseline"].map(pct),
                        difference_pts=iv["difference_pts"].map(lambda v: f"{v:+.1f}"))

    bridge = tables["bridge"].assign(late_rate=tables["bridge"]["late_rate"].map(pct))
    issues = validation[validation["failed"] > 0][["rule_id", "rule", "severity", "failed", "action"]]

    return f"""# Evidence table - run {run_id}

Generated by `run_pipeline.py`. Do not edit by hand.

## Metrics
{md_table(headline[["metric_id", "metric", "value", "numerator", "denominator", "definition"]])}

**M5 - interventions vs comparable orders** (orders that got no intervention but were in the same
stage at the same minute; negative = fewer late orders than expected)

{md_table(iv_view)}

When interventions happen (the dispatch estimate puts pickup at 18 min after creation):

{md_table(tables["intervention_timing"])}

## Where the delay accumulates (median minutes, KPI orders)
{md_table(tables["stages"])}

## From leadership's 56% to the KPI
{md_table(bridge)}

## Validation findings
{md_table(issues)}

## Reconciliation with the client's existing `order_outcomes.csv`
- orders compared: {reconciliation["orders_compared"]}, late-flag disagreements: {reconciliation["late_flag_disagreements"]}
- orders in our KPI that the reference marks unknown: {reconciliation["in_our_kpi_but_unknown_in_reference"]}
- late rate check: M1 = {pct(m.loc["M1", "value"])}
"""
